# Generated by Django 3.0.5 on 2020-04-14 12:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsModel',
            fields=[
                ('id', models.CharField(db_index=True, default=uuid.uuid4, max_length=50, primary_key=True, serialize=False)),
                ('method', models.CharField(max_length=200, null=True)),
                ('endpoint', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('response_time', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'logs',
            },
        ),
    ]
